name: CI-iOS

on:
  push:
    branches: [main, develop, hotfix/detox-github-action]

jobs:
  e2e-test:
    name: e2e iOS test
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache node_modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Pod dependencies
        run: cd ios && pod install && cd ..

      - name: Install Detox dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run Detox Build
        run: yarn build:e2e-ios-dev-debug

      - name: Run Detox Test(s)
        run: bash ${{ github.workspace }}/scripts/run-e2e-ios-release.sh
